<?php
define("TEXT_TITLE", "WEBTE Zadanie");
define("TEXT_LOGIN", "Prihlásenie");
define("TEXT_STUDENT", "Študent");
define("TEXT_ADMIN", "Admin");
define("TEXT_PASSWORD", "Heslo");
define("TEXT_BTN_LOGIN", "Prihlásiť sa");
define("TEXT_HOME", "Domov");
define("TEXT_TASK", "Úloha");
define("TEXT_TASK1", "Úloha 1");
define("TEXT_TASK2", "Úloha 2");
define("TEXT_TASK3", "Úloha 3");
define("TEXT_TASKS", "Rozdelenie úloh");
define("TEXT_NAME", "Meno");
define("TEXT_DOCUMENTATION", "Technická dokumentácia");
define("TEMPLATE", "Šablóna");
define("UPLOAD_DATA", "Upload dát");
define("SELECT_FILE", "Vyber súbor na spracovanie");
define("ADD_NEW_TEMPLATE", "Pridanie novej šablóny");
define("TEMPLATE_TITLE", "Názov šablóny");
define("SAVE_TEMPLATE", "Ulož šablónu");
define("SEND_EMAILS", "Odoslanie emailov");
define("SENDER_NAME", "Meno odosielateľa");
define("SENDER_EMAIL", "Email odosielateľa");
define("SENDER_PASSWORD", "Heslo odosielateľa");
define("EMAIL_SUBJECT", "Predmet emailu");
define("FILE_WITH_DATA", "Súbor s dátami");
define("ATTACHMENT", "Príloha");
define("STUDENT_NAME", "Meno študenta");
define("DATE", "Dátum");
define("TEMPLATE_ID", "ID Šablóny");
define("TEXT_ADMINONLY", "Iba pre admina");
define("TEXT_CHOOSEYEAR", "Vyber rok");
define("SENT_EMAILS_HISTORY", "História poslaných emailov");
define("TEXT_COURSETABLE", "Tabuľky s bodmi");
define("TEXT_ERROR", "Vyskytla sa chyba");
define("TEXT_MULTILANG", "Dvojjazyčnosť");
define("TEXT_COURSENAME", "Názov predmetu");
define("TEXT_SELECTFILE", "Vybrať súbor");
define("TEXT_DELIMITER", "Oddeľovač");
define("TEXT_SHOWTABLES", "Zobraziť tabuľku vybraného predmetu");
define("TEXT_DELETECOURSE", "Odstrániť predmet");
define("TEXT_UPLOADFILE", "Nahrať súbor");
define("TEXT_CREATEFOLDER", "Vytvoriť priečinok pre nový rok");
define("TEXT_SUBMIT", "Odoslať");
define("TEXT_CHOOSECOURSE", "Vyber predmet");
define("TEXT_DOWNLOADTABLE", "Stiahnuť tabuľku ako pdf");

define("U2_", "SK");
define("U2_PRIHLASENY", "Prihlásený je");
define("U2_VYBER_PREDMET", "Vyber predmet");
define("U2_VYBRAT_PREDMET", "Vybrať predmet");
define("U2_VYBRANY_PREDMET_JE", "Vybraný predmet je");
define("U2_TIM_CISLO", "Si v tíme s číslom ");
define("U2_TIM_ZISKAL", ", tento tím má ");
define("U2_TIM_BODOV", " bodov.");
define("U2_TIM_BODOV2", " bodov, ešte je nerozdelených ");
define("U2_TIM_ROZDELENE_BODY", "Tvoj tím má už rozdelených ");
define("U2_TIM_SI_KAPITAN", "Si kapitán tímu, možeš prideľovať body členom tímu.");
define("U2_TIM_NIE_SI_KAPITAN", "Nie si kapitán tímu, nemôžeš prideľovať body členom tímu.");
define("U2_MENO", "MENO");
define("U2_SUHLAS_BODY", "SÚHLASENIE S BODMI");
define("U2_BODY", "BODY");
define("U2_MENENIE_BODOV", "MENENIE BODOV");
define("U2_SUHLAS", "súhlasí");
define("U2_NESUHLAS", "nesúhlasí");
define("U2_NEHLASOVAL", "nehlasoval");
define("U2_ZMENIT_BODY", "zmeniť body");
define("U2_SUHLAS2", "Súhlasím");
define("U2_NESUHLAS2", "Nesúhlasím");
define("U2_PRIHLASIT_SA", "Prihlásiť sa");
define("U2_ZLE_HESLO", "Zle heslo.");
define("U2_PRIHLASENY_AJ_CEZ_HESLO", "Bol si prihlásený aj za pomoci hesla.");
define("U2_VLOZIT_SUBOR", "Vlozit subor");
define("U2_ROK", "Rok");
define("U2_ODDELOVAC", "Oddelovac");
define("U2_PREDMET", "Predmet");
define("U2_STATS", "Štatistika");
define("U2_SUHLAST", "Odsúhlasených");
define("U2_NESUHLAST", "Neodsuhlasených");
define("U2_POCET_TIMOV", "Počet tímov");
define("U2_POCET_STUDENTOV", "Počet študentov");
define("U2_TEAM", "Tím");
?>