<?php
define("TEXT_TITLE", "WEBTE Zadanie");
define("TEXT_LOGIN", "Prihlásenie");
define("TEXT_STUDENT", "Študent");
define("TEXT_ADMIN", "Admin");
define("TEXT_PASSWORD", "Heslo");
define("TEXT_BTN_LOGIN", "Prihlásiť sa");
define("TEXT_HOME", "Domov");
define("TEXT_TASK", "Úloha");
define("TEXT_TASK1", "Úloha 1");
define("TEXT_TASK2", "Úloha 2");
define("TEXT_TASK3", "Úloha 3");
define("TEXT_TASKS", "Rozdelenie úloh");
define("TEXT_NAME", "Meno");
define("TEXT_DOCUMENTATION", "Technická dokumentácia");
define("TEMPLATE", "Sablona");
define("UPLOAD_DATA", "Upload dat");
define("SELECT_FILE", "Vyber subor na spracovanie");
define("ADD_NEW_TEMPLATE", "Pridanie novej sablony");
define("TEMPLATE_TITLE", "Nazov sablony");
define("SAVE_TEMPLATE", "Uloz sablonu");
define("SEND_EMAILS", "Odoslanie emailov");
define("SENDER_NAME", "Meno odosielatela");
define("SENDER_EMAIL", "Email odosielatela");
define("SENDER_PASSWORD", "Heslo odosielatela");
define("EMAIL_SUBJECT", "Subject emailu");
define("FILE_WITH_DATA", "Subor s datami");
define("ATTACHMENT", "Priloha");
define("STUDENT_NAME", "Meno studenta");
define("DATE", "Datum");
define("TEMPLATE_ID", "ID Sablony");
define("ERROR_SEND_EMAILS", "Nezadali see meno odosielatela, email odosielatela, heslo odosielatela, subjekt emailu, alebo subor s datami");
define("TEXT_ADMINONLY", "Iba pre admina");
define("TEXT_CHOOSEYEAR", "Vyber rok");
?>
