<?php
define("TEXT_TITLE", "WEBTE Zadanie");
define("TEXT_LOGIN", "Prihlásenie");
define("TEXT_STUDENT", "Študent");
define("TEXT_ADMIN", "Admin");
define("TEXT_PASSWORD", "Heslo");
define("TEXT_BTN_LOGIN", "Prihlásiť sa");
define("TEXT_HOME", "Domov");
define("TEXT_TASK", "Úloha");
define("TEXT_TASK1", "Úloha 1");
define("TEXT_TASK2", "Úloha 2");
define("TEXT_TASK3", "Úloha 3");
define("TEXT_TASKS", "Rozdelenie úloh");
define("TEXT_NAME", "Meno");
define("TEXT_DOCUMENTATION", "Technická dokumentácia");
define("TEMPLATE", "Šablóna");
define("UPLOAD_DATA", "Upload dát");
define("SELECT_FILE", "Vyber súbor na spracovanie");
define("ADD_NEW_TEMPLATE", "Pridanie novej šablóny");
define("TEMPLATE_TITLE", "Názov šablóny");
define("SAVE_TEMPLATE", "Ulož šablónu");
define("SEND_EMAILS", "Odoslanie emailov");
define("SENDER_NAME", "Meno odosielateľa");
define("SENDER_EMAIL", "Email odosielateľa");
define("SENDER_PASSWORD", "Heslo odosielateľa");
define("EMAIL_SUBJECT", "Predmet emailu");
define("FILE_WITH_DATA", "Súbor s dátami");
define("ATTACHMENT", "Príloha");
define("STUDENT_NAME", "Meno študenta");
define("DATE", "Dátum");
define("TEMPLATE_ID", "ID Šablóny");
define("TEXT_ADMINONLY", "Iba pre admina");
define("TEXT_CHOOSEYEAR", "Vyber rok");
define("SENT_EMAILS_HISTORY", "História poslaných emailov");
define("TEXT_COURSETABLE", "Tabuľky s bodmi");
define("TEXT_ERROR", "Vyskytla sa chyba");
define("TEXT_MULTILANG", "Dvojjazyčnosť");
define("TEXT_COURSENAME", "Názov predmetu");
define("TEXT_SELECTFILE", "Vybrať súbor");
define("TEXT_DELIMITER", "Oddeľovač");
define("TEXT_SHOWTABLES", "Zobraziť tabuľku vybraného predmetu");
define("TEXT_DELETECOURSE", "Odstrániť predmet");
define("TEXT_UPLOADFILE", "Nahrať súbor");
define("TEXT_CREATEFOLDER", "Vytvoriť priečinok pre nový rok");
define("TEXT_SUBMIT", "Odoslať");
define("TEXT_CHOOSECOURSE", "Vyber predmet");
define("TEXT_DOWNLOADTABLE", "Stiahnuť tabuľku ako pdf");
?>