<?php
define("TEXT_TITLE", "WEBTE Assignment");
define("TEXT_LOGIN", "Log in");
define("TEXT_STUDENT", "Student");
define("TEXT_ADMIN", "Admin");
define("TEXT_PASSWORD", "Password");
define("TEXT_BTN_LOGIN", "Log in");
define("TEXT_HOME", "Home");
define("TEXT_TASK", "Task");
define("TEXT_TASK1", "Task 1");
define("TEXT_TASK2", "Task 2");
define("TEXT_TASK3", "Task 3");
define("TEXT_TASKS", "Division of tasks");
define("TEXT_NAME", "Name");
define("TEXT_DOCUMENTATION", "Technical documentation");
define("TEMPLATE", "Template");
define("UPLOAD_DATA", "Upload data");
define("SELECT_FILE", "Select file to process");
define("ADD_NEW_TEMPLATE", "Add new template");
define("TEMPLATE_TITLE", "Template title");
define("SAVE_TEMPLATE", "Save template");
define("SEND_EMAILS", "Send emails");
define("SENDER_NAME", "Sender name");
define("SENDER_EMAIL", "Sender email");
define("SENDER_PASSWORD", "Sender password");
define("EMAIL_SUBJECT", "Email subject");
define("FILE_WITH_DATA", "File with data");
define("ATTACHMENT", "Attachment");
define("STUDENT_NAME", "Student name");
define("DATE", "Date");
define("TEMPLATE_ID", "Template ID");
define("TEXT_ADMINONLY", "Admin only");
define("TEXT_CHOOSEYEAR", "Choose year");
define("SENT_EMAILS_HISTORY", "History of sent emails");

define("U2_", "EN");
define("U2_PRIHLASENY", "Logged in is");
define("U2_VYBER_PREDMET", "Select subject");
define("U2_VYBRAT_PREDMET", "Select subject");
define("U2_VYBRANY_PREDMET_JE", "The selected subject is");
define("U2_TIM_CISLO", "You're in the team with the number ");
define("U2_TIM_ZISKAL", ", this team has ");
define("U2_TIM_BODOV", " points.");
define("U2_TIM_BODOV2", " points, still is undistributed ");
define("U2_TIM_ROZDELENE_BODY", "Your team has already divided ");
define("U2_TIM_SI_KAPITAN", "You are a team captain, you can allocate points to team members.");
define("U2_TIM_NIE_SI_KAPITAN", "You are not a team captain, you cannot allocate points to team members.");
define("U2_MENO", "NAME");
define("U2_SUHLAS_BODY", "AGREE WITH POINT");
define("U2_BODY", "POINTS");
define("U2_MENENIE_BODOV", "CHANGING POINTS");
define("U2_SUHLAS", "agree");
define("U2_NESUHLAS", "disagree");
define("U2_NEHLASOVAL", "not voted");
define("U2_ZMENIT_BODY", "change points");
define("U2_SUHLAS2", "Agree");
define("U2_NESUHLAS2", "Disagree");
define("U2_PRIHLASIT_SA", "Sing in");
define("U2_ZLE_HESLO", "Wrong password.");
define("U2_PRIHLASENY_AJ_CEZ_HESLO", "You were also logged in with a password.");
