<?php
define("TEXT_TITLE", "WEBTE Assignment");
define("TEXT_LOGIN", "Log in");
define("TEXT_STUDENT", "Student");
define("TEXT_ADMIN", "Admin");
define("TEXT_PASSWORD", "Password");
define("TEXT_BTN_LOGIN", "Log in");
define("TEXT_HOME", "Home");
define("TEXT_TASK", "Task");
define("TEXT_TASK1", "Task 1");
define("TEXT_TASK2", "Task 2");
define("TEXT_TASK3", "Task 3");
define("TEXT_TASKS", "Division of tasks");
define("TEXT_NAME", "Name");
define("TEXT_DOCUMENTATION", "Technical documentation");
define("TEMPLATE", "Template");
define("UPLOAD_DATA", "Upload data");
define("SELECT_FILE", "Select file to process");
define("ADD_NEW_TEMPLATE", "Add new template");
define("TEMPLATE_TITLE", "Template title");
define("SAVE_TEMPLATE", "Save template");
define("SEND_EMAILS", "Send emails");
define("SENDER_NAME", "Sender name");
define("SENDER_EMAIL", "Sender email");
define("SENDER_PASSWORD", "Sender password");
define("EMAIL_SUBJECT", "Email subject");
define("FILE_WITH_DATA", "File with data");
define("ATTACHMENT", "Attachment");
define("STUDENT_NAME", "Student name");
define("DATE", "Date");
define("TEMPLATE_ID", "Template ID");
define("TEXT_ADMINONLY", "Admin only");
define("TEXT_CHOOSEYEAR", "Choose year");
define("SENT_EMAILS_HISTORY", "History of sent emails");
define("TEXT_COURSETABLE", "Tables with points");
define("TEXT_ERROR", "Error occurred");
define("TEXT_MULTILANG", "Multi-language support");
define("TEXT_COURSENAME", "Course name");
define("TEXT_SELECTFILE", "Select file");
define("TEXT_DELIMITER", "Delimiter");
define("TEXT_SHOWTABLES", "Show table of selected course");
define("TEXT_DELETECOURSE", "Delete course");
define("TEXT_UPLOADFILE", "Upload file");
define("TEXT_CREATEFOLDER", "Create folder for new year");
define("TEXT_SUBMIT", "Submit");
define("TEXT_CHOOSECOURSE", "Choose course");
define("TEXT_DOWNLOADTABLE", "Download table as pdf");
?>